_BASE_: ../../../configs/Base-bagtricks.yml

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)
MODEL:
  BACKBONE:
    NAME: build_resnet_backbone_prune
  META_ARCHITECTURE: Baseline

SOLVER:
  AMP:
    ENABLED: False
  OPT: Adam
  MAX_EPOCH: 120
  BASE_LR: 0.000035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
  IMS_PER_BATCH: 64

  SCHED: MultiStepLR
  STEPS: [ 30 ]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 0

  CHECKPOINT_PERIOD: 30

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/market1501/bagtricks_R50_prune