_BASE_: ../../../configs/Base-bagtricks.yml

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)
MODEL:
  BACKBONE:
    NAME: build_resnet_backbone_distill
    # NAME: build_resnet_backbone_prune
  # META_ARCHITECTURE: Baseline
  META_ARCHITECTURE: Distiller

KD:
  MODEL_CONFIG: ("logs/market1501/bagtricks_R50_ibn_reproduce/distill_config.yaml",)
  MODEL_WEIGHTS: ("logs/market1501/bagtricks_R50_ibn_reproduce/model_best.pth",)


SOLVER:
  AMP:
    ENABLED: False
  OPT: Adam
  MAX_EPOCH: 120
  BASE_LR: 0.000035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005
  IMS_PER_BATCH: 64

  SCHED: MultiStepLR
  STEPS: [ 60 ]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 0

  CHECKPOINT_PERIOD: 30

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/market1501/bagtricks_R50_prune_distill